FROM node:20-alpine

WORKDIR /app


# Install deps
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy source
COPY . .

ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_ENCRYPT_KEY
ARG ENCRYPT_SECRET_KEY
ARG NEXT_SITE_BASE_URL


ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_ENCRYPT_KEY=$NEXT_PUBLIC_ENCRYPT_KEY
ENV ENCRYPT_SECRET_KEY=$ENCRYPT_SECRET_KEY
ENV NEXT_SITE_BASE_URL=$NEXT_SITE_BASE_URL


# Build Next.js
RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
